export const ActionTypes = {
  GET_USERS: "GET_USERS",
  GET_USER: "GET_USER",
  ADD_USERS: "ADD_USERS",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT: "GET_PRODUCT",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRODUCTS_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_QUANTITY: "SET_QUANTITY",
};
